version: 25
jobs:
- name: pull
  steps:
  - !PullRepository
    name: pull
    remoteUrl: https://github.com/RickyGu777/halo-plugin-publish.git
    syncToChildProject: false
    passwordSecret: github_sync
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !ScheduleTrigger
    cronExpression: 0 0 1 * * ?
    projects: halo-plugin-publish
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
